# Generated by Django 5.0.6 on 2024-07-07 21:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50)),
                ('finance_entry_type', models.IntegerField(choices=[(1, 'DEPENSE'), (2, 'REVENUE')])),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'entry_category',
            },
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_entry_type', models.IntegerField(choices=[(1, 'DEPENSE'), (2, 'REVENUE')])),
                ('entry_value', models.FloatField(default=0)),
                ('entry_label', models.CharField(max_length=20)),
                ('entry_date', models.DateField(default=datetime.datetime(2024, 7, 7, 21, 47, 20, 650220, tzinfo=datetime.timezone.utc))),
                ('entry_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.entrycategory')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'db_table': 'finance_entries',
            },
        ),
    ]
