# Generated by Django 5.0.6 on 2024-07-17 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_financeentry_entry_date_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 15, 46, 7, 124453, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
