# Generated by Django 5.0.6 on 2024-07-17 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_financeentry_entry_date_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 18, 41, 24, 23897, tzinfo=datetime.timezone.utc)),
        ),
    ]
